/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/exception": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AUTH_001AUTH_002AUTH_003GLOBAL_001JWT_001JWT_002JWT_003JWT_004JWT_005JWT_006MEMBER_SECURITY_001NODE_001NODE_002NODE_003NODE_004NODE_005NODE_006NODE_007REQ_001REQ_002REQ_003SECURITY_001"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 노드 내용 수정 API
         * @description 노드 내용 수정 API
         */
        patch: operations["node-content-modify-patch"];
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 노드 추가 API
         * @description 노드 추가 API
         */
        post: operations["node-add-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 로컬 로그인 API
         * @description 회원 로컬 로그인 API
         */
        post: operations["local-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login-init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인 사전 정보 조회 API
         * @description 로그인 사전 정보 조회 API
         */
        post: operations["login-init"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계정 복구 API
         * @description 복구 코드를 인증하여 보안 정보를 갱신하고 로그인을 수행합니다.
         */
        post: operations["member-recovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recovery-init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계정 복구 사전 정보 조회 API
         * @description 비밀번호 분실 시 계정 복구를 위한 사전 정보(솔트 및 KDF 파라미터) 조회 API
         */
        post: operations["recovery-init"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 가입 API
         * @description 회원 가입 API
         */
        post: operations["local-signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 본인 계정 조회 API
         * @description 본인 계정 조회 API
         */
        get: operations["member-me"];
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴 API
         * @description 현재 로그인한 회원의 정보를 삭제하고 탈퇴 처리를 진행합니다.
         */
        delete: operations["member-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-contents/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 노드 내용 삭제 API
         * @description 노드 내용 삭제 API
         */
        post: operations["node-content-delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 노드 트리 조회 API
         * @description 전체 노드 트리 조회 API
         */
        get: operations["node-tree-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 특정 노드의 상세 내용 전체 조회 API
         * @description 특정 노드의 상세 내용 전체 조회 API
         */
        get: operations["node-detail-get"];
        put?: never;
        post?: never;
        /**
         * 노드 삭제 API
         * @description 노드 삭제 API
         */
        delete: operations["node-remove-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 노드 내용 추가 API
         * @description 노드 내용 추가 API
         */
        post: operations["node-content-add-post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 노드 이동 API
         * @description 노드 이동 API
         */
        patch: operations["node-move-patch"];
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 노드 제목 수정 API
         * @description 노드 제목 수정 API
         */
        patch: operations["node-title-modify-patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** MemberLoginRequest */
        MemberLoginRequest: {
            /** @description 비밀번호 기반 인증용 해시값 */
            passwordAuthHash: string;
            /** @description 로그인 시도할 회원 id (이메일 등) */
            loginId: string;
        };
        /** VoidResponse */
        VoidResponse: {
            /** @description 응답 상태 코드 (ex: ok) */
            code: string;
            /** @description 결과 메시지 (ex: ok) */
            data: string;
            /** @description 응답 메시지 */
            message: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** MemberCreateRequest */
        MemberCreateRequest: {
            /** @description KDF 파라미터 */
            kdfParam: {
                /** @description 출력 키 길이 bytes 단위 (최소 32) */
                keyLength: number;
                /** @description 메모리 사용량 KB 단위 (최소 19456) */
                memory: number;
                /** @description 병렬 처리 수 (최소 1) */
                parallelism: number;
                /** @description 반복 횟수 (최소 2) */
                iterations: number;
                /** @description KDF 알고리즘 (예: ARGON2ID) */
                algorithm: string;
            };
            /** @description 비밀번호 분실 대비 복구키로 암호화된 DEK */
            recoveryEncryptedDek: string;
            /** @description 비밀번호 기반 인증용 해시값 */
            passwordAuthHash: string;
            /** @description 회원 로그인 id (이메일 등) */
            loginId: string;
            /** @description 사용자의 메인 KEK로 암호화된 데이터 암호화 키 (DEK) */
            passwordEncryptedDek: string;
            /** @description 복구키 해시 생성에 사용된 고유 솔트값 */
            recoverySalt: string;
            /** @description 복구키 기반 인증용 해시값 */
            recoveryAuthHash: string;
            /** @description 비밀번호 해시 생성에 사용된 고유 솔트값 */
            passwordSalt: string;
        };
        /** LoginInitResponse */
        LoginInitResponse: {
            /** @description 코드 */
            code: string;
            /** @description 응답 데이터 */
            data: {
                /** @description 클라이언트 KDF 파라미터 정보 */
                kdfParam: {
                    /** @description 출력 키 길이 bytes 단위 (최소 32) */
                    keyLength: number;
                    /** @description 메모리 사용량 KB 단위 (최소 19456) */
                    memory: number;
                    /** @description 병렬 처리 수 (최소 1) */
                    parallelism: number;
                    /** @description 반복 횟수 (최소 2) */
                    iterations: number;
                    /** @description KDF 알고리즘 (예: argon2id) */
                    algorithm: string;
                };
                /** @description 해시 생성에 사용된 고유 솔트값 */
                passwordSalt: string;
            };
            /** @description 메시지 */
            message: string;
            /** @description 상태 */
            status: number;
        };
        /** NodeTreeResponse */
        NodeTreeResponse: {
            /** @description 응답 상태 코드 (ex: ok) */
            code: string;
            /** @description 노드 트리 리스트 */
            data: {
                /** @description 부모 노드의 식별자 ID (최상위 루트 폴더인 경우 null) */
                nodeParentId?: number | null;
                /** @description 종단간 암호화(E2EE)가 적용된 노드 제목 */
                encryptedTitle: string;
                /** @description 노드의 종류 (FOLDER 또는 FILE) */
                nodeType: string;
                /** @description 노드의 고유 식별자(ID) */
                nodeId: number;
            }[];
            /** @description 응답 메시지 */
            message: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** MemberLoginInitRequest */
        MemberLoginInitRequest: {
            /** @description 로그인 시도할 회원 id (이메일 등) */
            loginId: string;
        };
        /** MemberRecoveryRequest */
        MemberRecoveryRequest: {
            /** @description 새로운 비밀번호 기반 인증 해시 */
            newPasswordAuthHash: string;
            /** @description 회원 로그인 id */
            loginId: string;
            /** @description 새로운 비밀번호용 솔트 */
            newPasswordSalt: string;
            /** @description 새로 적용할 KDF 파라미터 */
            newKdfParam: {
                /** @description 키 길이 */
                keyLength: number;
                /** @description 메모리 사용량 */
                memory: number;
                /** @description 병렬 처리 수 */
                parallelism: number;
                /** @description 반복 횟수 */
                iterations: number;
                /** @description KDF 알고리즘 */
                algorithm: string;
            };
            /** @description 새로운 비밀번호(KEK)로 암호화된 DEK */
            newPasswordEncryptedDek: string;
            /** @description 기존 복구키 기반 인증 해시 */
            recoveryAuthHash: string;
        };
        /** MemberMeResponse */
        MemberMeResponse: {
            /** @description 코드 */
            code: string;
            /** @description 응답 데이터 */
            data: {
                /** @description 회원 로그인 id */
                loginId: string;
                /** @description 가입 권한 - ACCOUNT_AUTH, PASSKEY */
                authMethod?: string | null;
                /** @description 회원 ID */
                memberId: number;
            };
            /** @description 에러 메시지 */
            message: string;
            /** @description 상태 */
            status: number;
        };
        /** NodeCreateRequest */
        NodeCreateRequest: {
            /** @description 위치 지정을 위한 다음(하단) 노드 ID (없을 시 null) */
            nextNodeId?: number | null;
            /** @description 위치 지정을 위한 이전(상단) 노드 ID (없을 시 null) */
            prevNodeId?: number | null;
            /** @description 종단간 암호화(E2EE)가 적용된 노드 제목 */
            encryptedTitle: string;
            /** @description 생성할 노드의 부모 ID (최상위 루트에 생성 시 null) */
            parentNodeId?: number | null;
            /** @description 생성할 노드의 종류 (FOLDER 또는 FILE) */
            nodeType: string;
        };
        /** MemberRecoveryInitResponse */
        MemberRecoveryInitResponse: {
            /** @description 코드 */
            code: string;
            /** @description 응답 데이터 */
            data: {
                /** @description 클라이언트 KDF 파라미터 정보 */
                kdfParam: {
                    /** @description 출력 키 길이 bytes 단위 (최소 32) */
                    keyLength: number;
                    /** @description 메모리 사용량 KB 단위 (최소 19456) */
                    memory: number;
                    /** @description 병렬 처리 수 (최소 1) */
                    parallelism: number;
                    /** @description 반복 횟수 (최소 2) */
                    iterations: number;
                    /** @description KDF 알고리즘 (예: argon2id) */
                    algorithm: string;
                };
                /** @description 복구 키에 따른 암호화된 DEK */
                recoveryEncryptedDek: string;
                /** @description 복구 키 해시 생성에 사용된 고유 솔트값 */
                recoverySalt: string;
            };
            /** @description 메시지 */
            message: string;
            /** @description 상태 */
            status: number;
        };
        /** NodeContentCreateRequest */
        NodeContentCreateRequest: {
            /** @description 종단간 암호화(E2EE)가 적용된 본문 내용 */
            encryptedContents: (Record<string, never> | boolean | string | number)[];
            /** @description 위치 지정을 위한 다음(하단) 블록 ID (없을 시 null) */
            nextNodeContentId?: number | null;
            /** @description 위치 지정을 위한 이전(상단) 블록 ID (없을 시 null) */
            prevNodeContentId?: number | null;
        };
        /** NodeFileResponse */
        NodeFileResponse: {
            /** @description 응답 상태 코드 (ex: ok) */
            code: string;
            /** @description 노드(파일)의 상세 내용 블록 리스트 */
            data: {
                /** @description 상세 내용 블록의 고유 식별자(ID) */
                nodeContentId: number;
                /** @description 종단간 암호화(E2EE)가 적용된 본문 내용 */
                encryptedContent: string;
            }[];
            /** @description 응답 메시지 */
            message: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-exception-1466924442": {
            /** @description 코드 */
            code: string;
            /** @description 응답 데이터 */
            data?: string | null;
            /** @description API 접근 권한이 없을때 생기는 오류 */
            message: string;
            /** @description 상태 */
            status: number;
        };
        /** NodeContentCreateResponse */
        NodeContentCreateResponse: {
            /** @description 응답 상태 코드 (ex: ok) */
            code: string;
            /** @description 생성된 노드 컨텐츠 응답 데이터 리스트 */
            data: {
                /** @description 새로 생성된 노드 컨텐츠의 고유 ID */
                nodeContentId: number;
            }[];
            /** @description 응답 메시지 */
            message: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** MemberLoginResponse */
        MemberLoginResponse: {
            /** @description 코드 */
            code: string;
            /** @description 응답 데이터 */
            data: {
                /** @description 암호화된 마스터 키 */
                passwordEncryptedDek: string;
                /** @description JWT 액세스 토큰 */
                accessToken: string;
            };
            /** @description 에러 메시지 */
            message: string;
            /** @description 상태 */
            status: number;
        };
        /** NodeTitleUpdateRequest */
        NodeTitleUpdateRequest: {
            /** @description 수정할 종단간 암호화(E2EE)가 적용된 노드 제목 */
            encryptedTitle: string;
        };
        /** NodeContentBatchUpdateRequest */
        NodeContentBatchUpdateRequest: {
            /** @description 수정할 노드 내용(블록) 요청 목록 */
            requests: {
                /** @description 수정할 대상 노드 내용(블록)의 고유 ID */
                nodeContentId: number;
                /** @description 수정할 종단간 암호화(E2EE)가 적용된 본문 내용 */
                encryptedContent: string;
            }[];
        };
        /** NodeMoveRequest */
        NodeMoveRequest: {
            /** @description 위치 지정을 위한 다음(하단) 노드 ID (없을 시 null) */
            nextNodeId?: number | null;
            /** @description 위치 지정을 위한 이전(상단) 노드 ID (없을 시 null) */
            prevNodeId?: number | null;
            /** @description 이동할 위치의 부모 노드 ID (최상위 루트로 이동 시 null) */
            parentNodeId?: number | null;
        };
        /** MemberRecoveryInitRequest */
        MemberRecoveryInitRequest: {
            /** @description 계정 복구를 시도할 회원 id (이메일 등) */
            loginId: string;
        };
        /** MemberRecoveryResponse */
        MemberRecoveryResponse: {
            /** @description 코드 */
            code: string;
            /** @description 응답 데이터 */
            data: {
                /** @description 새로 발급된 JWT 액세스 토큰 */
                accessToken: string;
            };
            /** @description 메시지 */
            message: string;
            /** @description 상태 */
            status: number;
        };
        /** NodeContentDeleteRequest */
        NodeContentDeleteRequest: {
            /** @description 수정할 노드 내용(블록) 요청 목록 id */
            nodeContentIds: (Record<string, never> | boolean | string | number)[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AUTH_001AUTH_002AUTH_003GLOBAL_001JWT_001JWT_002JWT_003JWT_004JWT_005JWT_006MEMBER_SECURITY_001NODE_001NODE_002NODE_003NODE_004NODE_005NODE_006NODE_007REQ_001REQ_002REQ_003SECURITY_001: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-exception-1466924442"];
                };
            };
        };
    };
    "node-content-modify-patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NodeContentBatchUpdateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
    "node-add-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NodeCreateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
    "local-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MemberLoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberLoginResponse"];
                };
            };
        };
    };
    "login-init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MemberLoginInitRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginInitResponse"];
                };
            };
        };
    };
    "member-recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MemberRecoveryRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRecoveryResponse"];
                };
            };
        };
    };
    "recovery-init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MemberRecoveryInitRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRecoveryInitResponse"];
                };
            };
        };
    };
    "local-signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MemberCreateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
    "member-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberMeResponse"];
                };
            };
        };
    };
    "member-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
    "node-content-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NodeContentDeleteRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
    "node-tree-get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTreeResponse"];
                };
            };
        };
    };
    "node-detail-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeFileResponse"];
                };
            };
        };
    };
    "node-remove-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
    "node-content-add-post": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NodeContentCreateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeContentCreateResponse"];
                };
            };
        };
    };
    "node-move-patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NodeMoveRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
    "node-title-modify-patch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NodeTitleUpdateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidResponse"];
                };
            };
        };
    };
}
